### ISSUE TITLE
How to reduce percentage

### ISSUE THREAD

**Issue by DKunin** [davidguttman/node-dataframe#4]
Hi there!

Thanks for great module, it's a great deal of help. Need a little help - so in my table I need to use percentages - is the only way to populate the table is to make dynamic reduce function, which will calculate percentage on the fly - or is it possible to use percentage from the start place?

**Comment by davidguttman** [comment]
I suppose it depends on your data, but most likely you'll have to have the division in your reduce function:

``` js
function reduce (row, memo) {
  memo.nMale = memo.nMale || 0
  memo.nFemale = memo.nFemale || 0
  memo.nTotal = memo.nTotal || 0

  if (row.gender === 'male') {
    memo.nMale += 1
  } else {
    memo.nFemale += 1
  }

  memo.nTotal += 1

  memo.percentMale = 100 * memo.nMale / memo.nTotal
  memo.percentFemale = 100 * memo.nFemale / memo.nTotal

  return memo
}
```

**Comment by DKunin** [comment]
Thanks for quick response, sorry for long response - didn't get the notification for some reason!

Great solution, thanks!
